# Generated by Django 2.2.7 on 2019-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('businessId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Business ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('companyForm', models.CharField(max_length=20, verbose_name='Company form')),
                ('detailsUri', models.CharField(max_length=20)),
            ],
        ),
    ]
