# Generated by Django 2.2.7 on 2019-11-29 13:47

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(businessId="1234567-8", name="TestiFirma", registrationDate="12-12-2020", companyForm="Oy", detailsUri="https:\\testi.fi").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
    ]
